name: projeto_financeiro
description: "Aplicativo de controle financeiro pessoal."

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  fl_chart: ^0.70.2
  flutter_svg: ^1.1.6
  font_awesome_flutter: ^10.7.0
  provider: ^6.0.0
  shared_preferences: ^2.2.2
  uuid: ^4.5.1
  http: ^1.3.0
  intl: 0.18.1
  firebase_core: ^3.12.1
  firebase_storage: ^12.4.6
  firebase_auth: ^5.5.1
  cloud_firestore: ^5.6.8
  flutterfire_cli: any
  image_picker: ^1.1.2
  flutter_local_notifications: ^18.0.1
  google_fonts: ^6.1.0
  syncfusion_flutter_charts: ^29.1.40
  google_sign_in: ^6.1.4


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
  

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"