// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDZMDtzQ9YRzXsUHQ-D1DdmgH6s7WUdfk',
    appId: '1:238748889820:web:25845c1c35f023f3487a19',
    messagingSenderId: '238748889820',
    projectId: 'tcc5periodo',
    authDomain: 'tcc5periodo.firebaseapp.com',
    storageBucket: 'tcc5periodo.firebasestorage.app',
    measurementId: 'G-MPX90V6L5C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1Ac9QwM5IKzep2Y78671v6GaE_0kGe2w',
    appId: '1:238748889820:android:341789dc87e8c27a487a19',
    messagingSenderId: '238748889820',
    projectId: 'tcc5periodo',
    storageBucket: 'tcc5periodo.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZ-B0UCO_jL6LgZUsVECYT4ZDTHlyPP1Q',
    appId: '1:238748889820:ios:843855feeb94a3ce487a19',
    messagingSenderId: '238748889820',
    projectId: 'tcc5periodo',
    storageBucket: 'tcc5periodo.firebasestorage.app',
    iosBundleId: 'com.example.projetoFinanceiro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBZ-B0UCO_jL6LgZUsVECYT4ZDTHlyPP1Q',
    appId: '1:238748889820:ios:843855feeb94a3ce487a19',
    messagingSenderId: '238748889820',
    projectId: 'tcc5periodo',
    storageBucket: 'tcc5periodo.firebasestorage.app',
    iosBundleId: 'com.example.projetoFinanceiro',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCDZMDtzQ9YRzXsUHQ-D1DdmgH6s7WUdfk',
    appId: '1:238748889820:web:74e9f1cc003454d4487a19',
    messagingSenderId: '238748889820',
    projectId: 'tcc5periodo',
    authDomain: 'tcc5periodo.firebaseapp.com',
    storageBucket: 'tcc5periodo.firebasestorage.app',
    measurementId: 'G-3XSKJYXSK9',
  );
}
